name: 'Cron'
on: 
  workflow_dispatch:
  #schedule:
  #- cron: '30 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: AKS Login
      uses: wemogy/aks-login-action@1.2.1
      with:
        name: my-aks-cluster
        resource-group: myResourceGroup-brief7
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        
    - name: Get last version + updating
      run: |
        sudo snap install jq
        VERSION=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq -r '."results"[0]["name"]')
        sed -i "s/@VERSION_APP@/$VERSION/" model.yml
        echo "Updating to azure_voting_app:$VERSION"
        kubectl apply -f model.yml
