name: 'GitLab trigger'
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger pipeline
      run: |
        curl -X POST --fail -F token=glptt-b56caaf9f2bf0adbcd177165bea59a426bf9e79a -F ref=main https://gitlab.com/api/v4/projects/35808802/trigger/pipeline
