name: 'Terraform Docker'
on: [workflow_dispatch]

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  publish:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: "./terraform"
    
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 20.172.251.107
        username: azureuser
        key: ${{ secrets.KEY }}
        port: 22
        script: whoami
