name: 'Update version'
on: 
  workflow_dispatch:
  #schedule:
  #- cron: '30 * * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: |
        ls -la
        pwd
        sudo snap install jq
        VERSION=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq -r '."results"[0]["name"]')
        sed -i "s/@VERSION_APP@/$VERSION/" voting-app-model.yml
        kubectl apply -f voting-app-model.yml
