name: 'Update version'
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: "./"
        
    steps:
    - name: Update
      run: |
        sudo snap install jq
        VERSION=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]' | sed 's/"//g; s/}//g')
        sed -i "s/\$VERSION/$VERSION/" voting-app-model.yml
        kubectl apply -f voting-app-model.yml
        
